import type {
  DeproAgent,
  DeproContract,
} from '../../types'

function ipo(
  input: string,
  processing: string,
  output: string,
): DeproContract {
  return { input, processing, output }
}

export const AGENT_CATALOG: DeproAgent[] = [
  {
    id: 'escriba',
    name: 'Escriba',
    typology: 'vectorizador',
    contract: ipo(
      'Audio (m4a, mp3, wav) en Zona franca.',
      'Deepgram STT, diarización y corte si el archivo es largo.',
      'Transcripción + entry en cola hacia Aduana.',
    ),
    domains: ['captura'],
    powerIndexes: [0],
    module: 'pipeline',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'Ya vive en server/services/pipeline.ts y deepgram.ts.',
  },
  {
    id: 'blob',
    name: 'Blob',
    typology: 'vectorizador',
    contract: ipo(
      'Nota rápida con @personas @proyectos @agrupaciones.',
      'Destila un quántomo (Cohere o heurística).',
      'Entry/quantomo enlazado sin pasar por STT.',
    ),
    domains: ['captura'],
    powerIndexes: [1],
    module: 'blobIngest',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'BlobComposer en Zona franca.',
  },
  {
    id: 'partidor',
    name: 'Partidor',
    typology: 'ejecutivo',
    contract: ipo(
      'Audio largo que no entra de una.',
      'Split por tiempo/silencio y reencola segmentos.',
      'Hijos de un split_parent listos para STT.',
    ),
    domains: ['captura'],
    powerIndexes: [3],
    module: 'audioSplit',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'server/services/audioSplit.ts',
  },
  {
    id: 'destilador',
    name: 'Destilador',
    typology: 'generativo',
    contract: ipo(
      'Transcripción o texto fuente.',
      'Cohere extract: título, quántomos, acciones, entidades.',
      'Proposal bundle para HITL.',
    ),
    domains: ['captura', 'memoria'],
    powerIndexes: [4, 34],
    module: 'cohere',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: 'extractFromTranscript / extractFromBookmark / extractFromChatBlock',
    notes: 'El corazón LLM actual. Command + Vision + Embed.',
  },
  {
    id: 'aduanero',
    name: 'Aduanero',
    typology: 'clasificador',
    contract: ipo(
      'Entry pending_criba (audio + transcript).',
      'HITL: peso 1–12, speakers↔personas, título, tags.',
      'Pasa a extract o queda cribado.',
    ),
    domains: ['criba'],
    powerIndexes: [9, 12],
    module: 'customs',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'CustomsPanel + AudioCribaPanel. El peso todavía es manual.',
  },
  {
    id: 'cribador',
    name: 'Cribador',
    typology: 'clasificador',
    contract: ipo(
      'Bookmark Twitter/Instagram importado.',
      'Scoring HITL 1–12 y banda de media (slop / texto / STT / OCR).',
      'Cola process-high-value o SLOP.',
    ),
    domains: ['criba'],
    powerIndexes: [10, 13],
    module: 'bookmarks',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'CribaPanel. El enrich de reels está a medias.',
  },
  {
    id: 'sello',
    name: 'Sello',
    typology: 'ejecutivo',
    contract: ipo(
      'Proposal editada por el operador.',
      'Approve / reject, congela metadata, dispara embeddings y NER.',
      'Entry approved en Validada.',
    ),
    domains: ['criba'],
    powerIndexes: [16],
    module: 'proposals',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'La aduana que cierra el lote.',
  },
  {
    id: 'visionario',
    name: 'Visionario',
    typology: 'crawler',
    contract: ipo(
      'Foto de página o frame de reel.',
      'Unlimited-OCR o Cohere Vision: layout, texto, gráficos.',
      'Transcripción + vision_meta para validar.',
    ),
    domains: ['biblioteca', 'criba'],
    powerIndexes: [18],
    module: 'notebooks',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: 'analyzeNotebookPage / explainVideoFrame',
    notes: 'notebookOcr.ts + unlimitedOcr.ts.',
  },
  {
    id: 'exegeta',
    name: 'Exegeta',
    typology: 'generativo',
    contract: ipo(
      'Página validada (texto + visión).',
      'Explain + NER de cuaderno.',
      'Explanation, entidades, puente a entry/quantomo.',
    ),
    domains: ['biblioteca'],
    powerIndexes: [22, 25],
    module: 'notebooks',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: 'explainNotebookPage / extractNotebookEntities',
    notes: 'El comentario al margen del cuaderno.',
  },
  {
    id: 'conversador',
    name: 'Conversador',
    typology: 'vectorizador',
    contract: ipo(
      'Export .txt de chat, bloque por día.',
      'extractFromChatBlock: summary, quántomo, entidades, URLs.',
      'Entry + harvest de links.',
    ),
    domains: ['memoria'],
    powerIndexes: [27],
    module: 'chats',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: 'extractFromChatBlock',
    notes:
      'ChatsSection — solo import WhatsApp/redes. No es el chat del producto (ver Oráculo).',
  },
  {
    id: 'onomasta',
    name: 'Onomasta',
    typology: 'clasificador',
    contract: ipo(
      'Menciones crudas y entity_proposals.',
      'HITL create/link/merge + matchmakers.',
      'Grafo de personas, proyectos, agrupaciones limpio.',
    ),
    domains: ['memoria'],
    powerIndexes: [28],
    module: 'entities',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'EntityHub, NerValidationDeck, person/project matchmaker.',
  },
  {
    id: 'oraculo',
    name: 'Oráculo',
    typology: 'omnivoro',
    contract: ipo(
      'Pregunta del operador + entity_refs + historial del hilo.',
      'searchGraphContext + fichas ancladas → Cohere /v2/chat multi-turno.',
      'Respuesta grounded en el corpus de la RUN.',
    ),
    domains: ['memoria'],
    powerIndexes: [29],
    module: 'dialogo',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: 'chatWithCorpus',
    notes: 'DialogoSection + Dashboard Enter→hilo. Ver chat.md.',
  },
  {
    id: 'mnemosyne',
    name: 'Mnemosyne',
    typology: 'crawler',
    contract: ipo(
      'Texto de entries, personas, proyectos, links.',
      'Cohere Embed + Rerank.',
      'Vectores para typeahead semántico y suggested links.',
    ),
    domains: ['memoria'],
    powerIndexes: [31],
    module: 'embeddings',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'La memoria de largo plazo. Alimenta el retrieve del Oráculo.',
  },
  {
    id: 'sentinela',
    name: 'Sentinela',
    typology: 'omnivoro',
    contract: ipo(
      'Nacimiento (MD + catálogos + censo) o comando escrito de misión.',
      'Inspección → perfil; luego loop de tools allowlist + RAG (quántomos, perfil, skills, docs).',
      'Notas, cuellos de tiempo, skills en borrador HITL. No reescribe TypeScript.',
    ),
    domains: ['memoria'],
    powerIndexes: [71],
    module: 'sentinela',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: 'chatWithTools',
    notes: 'Motor de inferencia configurable (Groq / Ollama / Stealth / Cohere). Ver Config → Motor de Inferencia.',
  },
  {
    id: 'tejedor',
    name: 'Tejedor',
    typology: 'crawler',
    contract: ipo(
      'Co-ocurrencias + similarity de embeddings.',
      'Scoring de vínculos suggested vs confirmed.',
      'Aristas del grafo Babel y sandboxes.',
    ),
    domains: ['memoria', 'territorio'],
    powerIndexes: [32],
    module: 'graph',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'GraphWorkspace. Promote desde sandbox está a mano.',
  },
  {
    id: 'cronista',
    name: 'Cronista',
    typology: 'ejecutivo',
    contract: ipo(
      'Occurrences de entries/tasks en un rango.',
      'Escala Trinchera / Campamento / Castillo + ciclo 28.',
      'Agenda del día y de la semana.',
    ),
    domains: ['territorio'],
    powerIndexes: [36],
    module: 'calendar',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'No prioriza solo: muestra. Un Chronos que sugiera slots es IDA.',
  },
  {
    id: 'cartografo',
    name: 'Cartógrafo',
    typology: 'crawler',
    contract: ipo(
      'lat/lng, hex H3 o place AmazonA.',
      'Resolve occupancy + capas.',
      'Qué vive en ese territorio.',
    ),
    domains: ['territorio'],
    powerIndexes: [37, 43],
    module: 'map',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'MapaSection + h3geo.',
  },
  {
    id: 'campo',
    name: 'Campo',
    typology: 'ejecutivo',
    contract: ipo(
      'Listas tridente/lista6 y ciclo ayer/hoy/mañana.',
      'Celdas de matrices 3×3 y 6×6, neo-swap.',
      'Campo operativo del día.',
    ),
    domains: ['territorio'],
    powerIndexes: [40],
    module: 'amazona',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'AmazonA. Todavía no propone celdas solo.',
  },
  {
    id: 'omnivoro-nucleo',
    name: 'Omnívoro',
    typology: 'omnivoro',
    contract: ipo(
      'El organismo entero: módulos, 72 poderes, IDA.',
      'Metaanálisis y recorte de fichas a mejorar.',
      'Este núcleo. Deprocast que se lee a sí mismo.',
    ),
    domains: ['vitalidad', 'memoria'],
    powerIndexes: [71],
    module: 'deprocast',
    idaStage: 'aplicacion',
    status: 'vivo',
    promptStub: '',
    notes: 'Posición 1. No ejecuta LLM todavía: cataloga, sugiere, guarda el tablero.',
  },
  {
    id: 'diarizador',
    name: 'Diarizador',
    typology: 'clasificador',
    contract: ipo(
      'Audio con varios hablantes.',
      'Mapa speaker → persona, con sugerencia automática.',
      'Criba prellenada.',
    ),
    domains: ['criba', 'captura'],
    powerIndexes: [9],
    module: 'pipeline',
    idaStage: 'desarrollo',
    status: 'bosquejo',
    promptStub: '',
    notes: 'Deepgram ya diariza; falta el match automático a personas.',
  },
  {
    id: 'auto-peso',
    name: 'Auto-peso',
    typology: 'clasificador',
    contract: ipo(
      'Audio + transcript + contexto de la RUN.',
      'Sugerir peso hermético 1–12.',
      'Draft de criba; el operador confirma.',
    ),
    domains: ['criba'],
    powerIndexes: [12],
    module: 'customs',
    idaStage: 'investigacion',
    status: 'bosquejo',
    promptStub: '',
    notes: 'Hoy el peso es 100% humano.',
  },
  {
    id: 'media-enrich',
    name: 'Media enrich',
    typology: 'crawler',
    contract: ipo(
      'Reel/video de peso alto.',
      'Frames → Vision → ocr_json.',
      'Enrichment para el Destilador.',
    ),
    domains: ['criba'],
    powerIndexes: [13],
    module: 'bookmarks',
    idaStage: 'desarrollo',
    status: 'bosquejo',
    promptStub: 'analyzeReelFrames',
    notes: 'Parcialmente cableado en instagramMedia.',
  },
  {
    id: 'link-crawler',
    name: 'Link crawler',
    typology: 'crawler',
    contract: ipo(
      'URL harvest de chats/bookmarks.',
      'Fetch + summarize + embed.',
      'link_harvest crawled con contexto.',
    ),
    domains: ['memoria'],
    powerIndexes: [31],
    module: 'links',
    idaStage: 'investigacion',
    status: 'bosquejo',
    promptStub: '',
    notes: 'La tabla existe; el crawler no está cerrado.',
  },
  {
    id: 'explorador',
    name: 'Explorador',
    typology: 'crawler',
    contract: ipo(
      'Tema libre del operador (manual).',
      'Prompt 6×6 → Perplexity Pro (copiar/pegar) → ingest JSON.',
      'Pack listo para HITL (asimilar / descartar / fractalizar).',
    ),
    domains: ['memoria'],
    powerIndexes: [33],
    module: 'research',
    idaStage: 'investigacion',
    status: 'vivo',
    promptStub: 'explorador',
    notes: 'Vista Cuarentena: Generar Prompt + pegar JSON. API Sonar opcional (/research/run).',
  },
  {
    id: 'explorador-academico',
    name: 'Explorador académico',
    typology: 'crawler',
    contract: ipo(
      'Tema académico / técnico.',
      'Prompt 6×6 (manual) → ingest JSON → cuarentena.',
      'Mismo bandeja HITL que Explorador.',
    ),
    domains: ['memoria'],
    powerIndexes: [33],
    module: 'research',
    idaStage: 'investigacion',
    status: 'vivo',
    promptStub: 'explorador-academico',
    notes: 'Perfil de prompt; comparte poder 33 y módulo research.',
  },
  {
    id: 'explorador-mercado',
    name: 'Explorador mercado',
    typology: 'crawler',
    contract: ipo(
      'Tema de mercado / actores / regulación.',
      'Prompt 6×6 (manual) → ingest JSON → cuarentena.',
      'Mismo bandeja HITL que Explorador.',
    ),
    domains: ['memoria'],
    powerIndexes: [33],
    module: 'research',
    idaStage: 'investigacion',
    status: 'vivo',
    promptStub: 'explorador-mercado',
    notes: 'Perfil de prompt; comparte poder 33 y módulo research.',
  },
  {
    id: 'contable',
    name: 'Contable',
    typology: 'clasificador',
    contract: ipo(
      'Movimientos, facturas, notas de gasto.',
      'Clasificar cuenta, periodo, proyecto.',
      'Libro mayor consultable.',
    ),
    domains: ['finanzas'],
    powerIndexes: [45, 48],
    module: null,
    idaStage: 'investigacion',
    status: 'hueco',
    promptStub: '',
    notes: 'Dominio nuevo. No hay módulo todavía.',
  },
  {
    id: 'tributario',
    name: 'Tributario',
    typology: 'ejecutivo',
    contract: ipo(
      'Hechos contables + calendario fiscal.',
      'Obligaciones, vencimientos, alertas.',
      'Lista de deberes y evidencias.',
    ),
    domains: ['finanzas', 'derecho'],
    powerIndexes: [51],
    module: null,
    idaStage: 'investigacion',
    status: 'hueco',
    promptStub: '',
    notes: '',
  },
  {
    id: 'legista',
    name: 'Legista',
    typology: 'vectorizador',
    contract: ipo(
      'Norma, contrato, expediente, nota oral.',
      'Tematizar: fuero, partes, plazos, riesgo.',
      'Ficha jurídica enlazable a personas/proyectos.',
    ),
    domains: ['derecho'],
    powerIndexes: [54, 57],
    module: null,
    idaStage: 'investigacion',
    status: 'hueco',
    promptStub: '',
    notes: '',
  },
  {
    id: 'contractual',
    name: 'Contractual',
    typology: 'generativo',
    contract: ipo(
      'Borrador o cláusula + contexto de las partes.',
      'Redactar / contrastar / marcar huecos.',
      'Pacto versionado.',
    ),
    domains: ['derecho'],
    powerIndexes: [60],
    module: null,
    idaStage: 'investigacion',
    status: 'hueco',
    promptStub: '',
    notes: '',
  },
  {
    id: 'medico-archivo',
    name: 'Médico-archivo',
    typology: 'clasificador',
    contract: ipo(
      'Estudios, recetas, notas de consulta (nunca consejo clínico autónomo).',
      'Archivar por sistema, fecha, profesional.',
      'Carpeta de salud consultable por el operador.',
    ),
    domains: ['vitalidad'],
    powerIndexes: [63],
    module: null,
    idaStage: 'investigacion',
    status: 'hueco',
    promptStub: '',
    notes: 'Archivo, no diagnóstico.',
  },
  {
    id: 'entrenador',
    name: 'Entrenador',
    typology: 'ejecutivo',
    contract: ipo(
      'Carga, sueño, sesión, dolor.',
      'Leer el ciclo cuerpo/mente y proponer el día.',
      'Plan de carga/descanso.',
    ),
    domains: ['vitalidad'],
    powerIndexes: [67],
    module: null,
    idaStage: 'investigacion',
    status: 'hueco',
    promptStub: '',
    notes: 'Habla con el tridente Cuerpo del calendario.',
  },
  {
    id: 'nutricionista',
    name: 'Nutricionista',
    typology: 'generativo',
    contract: ipo(
      'Comidas, compras, analítica, preferencias.',
      'Patrones, déficits, ritmos.',
      'Mesa del día / de la semana.',
    ),
    domains: ['vitalidad'],
    powerIndexes: [70],
    module: null,
    idaStage: 'investigacion',
    status: 'hueco',
    promptStub: '',
    notes: '',
  },
  {
    id: 'soma',
    name: 'Soma',
    typology: 'omnivoro',
    contract: ipo(
      'Señal del cuerpo: sueño, pulso, dolor, entrenamiento.',
      'Traducir a Cuerpo del tridente.',
      'Ajuste táctico del día.',
    ),
    domains: ['vitalidad'],
    powerIndexes: [63],
    module: null,
    idaStage: 'investigacion',
    status: 'bosquejo',
    promptStub: '',
    notes: 'Agente-tridente. Todavía sin sensores.',
  },
  {
    id: 'noos',
    name: 'Noos',
    typology: 'omnivoro',
    contract: ipo(
      'Atención, lectura, criba, decisiones.',
      'Traducir a Mente.',
      'Qué merece foco hoy.',
    ),
    domains: ['vitalidad', 'memoria'],
    powerIndexes: [64],
    module: null,
    idaStage: 'investigacion',
    status: 'bosquejo',
    promptStub: '',
    notes: '',
  },
  {
    id: 'pneuma',
    name: 'Pneuma',
    typology: 'omnivoro',
    contract: ipo(
      'Rito, ánimo, sentido, ciclo 28.',
      'Traducir a Alma.',
      'Brújula, no task list.',
    ),
    domains: ['vitalidad'],
    powerIndexes: [65],
    module: null,
    idaStage: 'investigacion',
    status: 'bosquejo',
    promptStub: '',
    notes: 'Habla con solfeggio y el eclipse de Saturno del calendario.',
  },
]

export const AGENT_BY_ID: Record<string, DeproAgent> = Object.fromEntries(
  AGENT_CATALOG.map((a) => [a.id, a]),
)

export function agentsForPower(index: number): DeproAgent[] {
  return AGENT_CATALOG.filter((a) => a.powerIndexes.includes(index))
}
