import type { DeproModule } from '../../types'

export const MODULE_CATALOG: DeproModule[] = [
  {
    id: 'run',
    label: 'RUN / operador',
    does: 'Identidad del operador, día 0, wipe de nuevo usuario.',
    files: 'NewUserGate, server/services/run.ts',
    ipo: {
      input: 'Nombre del operador.',
      processing: 'Crear persona operador + embeddings.',
      output: 'AppRun activa.',
    },
    suggestedAgentIds: ['omnivoro-nucleo'],
  },
  {
    id: 'franca',
    label: 'Zona franca',
    does: 'Ingesta de audio y blobs.',
    files: 'FreeZone, BlobComposer, ingest.ts',
    ipo: {
      input: 'Archivo o nota.',
      processing: 'Vault + entry queued.',
      output: 'Cola visible.',
    },
    suggestedAgentIds: ['escriba', 'blob'],
  },
  {
    id: 'directo',
    label: 'Directo',
    does: 'Escucha continua del micrófono vía Deepgram Live (proxy WS en el server). Feed interim/final en sesión.',
    files: 'DirectoSection, live/deepgramLive.ts, liveWs.ts, routes/live.ts',
    ipo: {
      input: 'Audio del micrófono.',
      processing: 'Proxy WSS con API key server-side + PCM linear16.',
      output: 'Bloques de transcripción en memoria. Persistencia = El Cofre.',
    },
    suggestedAgentIds: ['escriba'],
  },
  {
    id: 'cofre',
    label: 'El Cofre',
    does: 'Extensión MV3: captura pantalla/pestaña + mic + STT live. Al detener, ingest a pending_criba (sin re-STT). Telemetría de pestaña por chrome.tabs (URL/título/permanencia; sin teclas).',
    files: 'extension/*, server/services/cofreIngest.ts, liveWs.ts',
    ipo: {
      input: 'Pantalla o pestaña + mic + timeline de navegación.',
      processing: 'Offscreen MediaRecorder + PCM al proxy Deepgram. POST /api/ingest/cofre.',
      output: 'Entry audio en pending_criba + cofre.json en vault.',
    },
    suggestedAgentIds: ['escriba'],
  },
  {
    id: 'pipeline',
    label: 'Pipeline de audio',
    does: 'STT → extract → review. Cola asíncrona.',
    files: 'pipeline.ts, deepgram.ts, audioSplit.ts, cohere.ts',
    ipo: {
      input: 'Entry audio.',
      processing: 'STT + LLM + persist.',
      output: 'Proposal / criba HITL.',
    },
    suggestedAgentIds: ['escriba', 'partidor', 'destilador', 'diarizador'],
  },
  {
    id: 'aduana',
    label: 'Aduana',
    does: 'HITL de audio: peso, speakers, approve.',
    files: 'CustomsPanel, AudioCribaPanel, proposals.ts',
    ipo: {
      input: 'Proposal + edits humanas.',
      processing: 'Approve + entity proposals + embed.',
      output: 'Entry approved.',
    },
    suggestedAgentIds: ['aduanero', 'auto-peso', 'sello'],
  },
  {
    id: 'criba',
    label: 'Criba de bookmarks',
    does: 'Twitter/Instagram: scoring, bandas, process-high-value.',
    files: 'CribaPanel, bookmarkProcess.ts',
    ipo: {
      input: 'Post/reel.',
      processing: 'STT/OCR/Cohere.',
      output: 'Categoría + quantomo + entities.',
    },
    suggestedAgentIds: ['cribador', 'media-enrich'],
  },
  {
    id: 'biblioteca',
    label: 'Biblioteca / cuadernos',
    does: 'Cuadernos físicos y digitales, OCR, validación de páginas.',
    files: 'BibliotecaSection, notebookOcr.ts, unlimitedOcr.ts',
    ipo: {
      input: 'Foto de página o source.',
      processing: 'Vision / OCR / explain.',
      output: 'Página validada + entidades.',
    },
    suggestedAgentIds: ['visionario', 'exegeta'],
  },
  {
    id: 'chats',
    label: 'Chats · import',
    does: 'Import .txt WhatsApp/redes, bloques por día, destilado. No es el chat del producto.',
    files: 'ChatsSection, chatProcess.ts',
    ipo: {
      input: 'Bloque de mensajes.',
      processing: 'extractFromChatBlock.',
      output: 'Entry/quantomo + URLs.',
    },
    suggestedAgentIds: ['conversador', 'link-crawler'],
  },
  {
    id: 'dialogo',
    label: 'Diálogo',
    does: 'Hilos operador ↔ Deprocast con RAG (entidades + corpus).',
    files: 'DialogoSection, DashboardSection, dialogo.ts, chat.md',
    ipo: {
      input: 'Pregunta + entity_refs.',
      processing: 'searchGraphContext + Cohere chat.',
      output: 'Respuesta grounded en la RUN.',
    },
    suggestedAgentIds: ['oraculo', 'mnemosyne'],
  },
  {
    id: 'sentinela',
    label: 'Sentinela',
    does: 'Instancias que inspeccionan producto y código, arman perfil y ejecutan misiones de análisis con pausa, logs y skills propias.',
    files: 'SentinelSection, sentinel.ts, alma-sentinela.md',
    ipo: {
      input: 'Nacimiento (harvest) o comando escrito.',
      processing: 'Inspección → perfil → loop de tools allowlist + RAG.',
      output: 'Notas, timings, skills HITL, perfil persistido.',
    },
    suggestedAgentIds: ['sentinela', 'mnemosyne'],
  },
  {
    id: 'validada',
    label: 'Validada',
    does: 'Archivo de entries approved, export JSON.',
    files: 'ValidatedSection',
    ipo: {
      input: 'Set approved.',
      processing: 'Index / export.',
      output: 'Corpus consultable.',
    },
    suggestedAgentIds: ['sello', 'mnemosyne'],
  },
  {
    id: 'entidades',
    label: 'Entidades',
    does: 'Personas, proyectos, agrupaciones, NER HITL.',
    files: 'EntityHub, matchmakers, entityRelations.ts',
    ipo: {
      input: 'Proposal + evidencia.',
      processing: 'Approve / merge / reject.',
      output: 'Grafo limpio.',
    },
    suggestedAgentIds: ['onomasta'],
  },
  {
    id: 'quantomos',
    label: 'Quántomos + links',
    does: 'Átomos de conocimiento y harvest de URLs.',
    files: 'QuantomosSection, linkHarvest.ts',
    ipo: {
      input: 'Texto o URL.',
      processing: 'Destilar / crawlear.',
      output: 'Nodo + embed.',
    },
    suggestedAgentIds: ['destilador', 'link-crawler'],
  },
  {
    id: 'grafo',
    label: 'Grafo + sandboxes',
    does: 'Babel 2D/3D, suggested links, promote.',
    files: 'GraphWorkspace, graph.ts, sandboxes.ts',
    ipo: {
      input: 'Co-ocurrencias + similarity.',
      processing: 'Scoring.',
      output: 'Aristas persistidas.',
    },
    suggestedAgentIds: ['tejedor', 'mnemosyne'],
  },
  {
    id: 'calendario',
    label: 'Calendario',
    does: 'Trinchera / Campamento / Castillo, ciclo 28, Amazona 72 geométrica.',
    files: 'calendario/*, lib/calendar/engine.ts',
    ipo: {
      input: 'Rango + occurrences.',
      processing: 'Escalar el tiempo.',
      output: 'Agenda.',
    },
    suggestedAgentIds: ['cronista'],
  },
  {
    id: 'amazona',
    label: 'AmazonA',
    does: 'Listas, matrices, geo, ciclo ayer/hoy/mañana.',
    files: 'AmazonaSection, amazona.ts',
    ipo: {
      input: 'Listas + contexto RUN.',
      processing: 'Celdas del ciclo.',
      output: 'Campo.',
    },
    suggestedAgentIds: ['campo'],
  },
  {
    id: 'mapa',
    label: 'Mapa',
    does: 'H3, capas, ocupación, radar.',
    files: 'mapa/*, h3geo.ts, map.ts',
    ipo: {
      input: 'Pick lat/lng o hex.',
      processing: 'Resolve place + occupancy.',
      output: 'Vista táctica.',
    },
    suggestedAgentIds: ['cartografo'],
  },
  {
    id: 'atlas',
    label: 'Atlas',
    does: 'Mapa administrativo y listado jerárquico (continente → nación → subdivisiones oficiales).',
    files: 'atlas/*, geografia.ts, geoGazetteerSeed.ts',
    ipo: {
      input: 'Gazetteer + peso del operador.',
      processing: 'Árbol parent_id + polígonos.',
      output: 'Canvas y lista de la misma fila.',
    },
    suggestedAgentIds: ['cartografo'],
  },
  {
    id: 'aleph',
    label: 'Aleph',
    does: 'Motor espacial: zoom logarítmico, LOD cósmico→micro, telemetría BPM/EEG, placeholders anatómicos.',
    files: 'AlephSection, UniverseEngine, aleph/*, aleph.md',
    ipo: {
      input: 'Cámara + sistemas + telemetría (BPM, EEG).',
      processing: 'LOD por distancia, pulso de escala, grafo de escena.',
      output: 'Vista espacial interactiva.',
    },
    suggestedAgentIds: ['soma', 'noos', 'cartografo'],
  },
  {
    id: 'respaldo',
    label: 'Respaldo',
    does: 'Export JSON/ZIP; fusionar o reemplazar; wipe de nuevo usuario.',
    files: 'RespaldoSection, backup.ts',
    ipo: {
      input: 'DB.',
      processing: 'Serialize.',
      output: 'Archivo portable.',
    },
    suggestedAgentIds: ['omnivoro-nucleo'],
  },
  {
    id: 'configuracion',
    label: 'Configuración',
    does: 'Selectores de proveedor/modelo por rol (LLM, STT, embed…). Keys en .env.',
    files: 'ConfiguracionSection, appSettings.ts, llmChat.ts',
    ipo: {
      input: 'Elección de proveedor.',
      processing: 'Persistir app_settings + router LLM.',
      output: 'Runtime multi-proveedor.',
    },
    suggestedAgentIds: ['omnivoro-nucleo'],
  },
  {
    id: 'feedback',
    label: 'Feedback',
    does: 'Captura de bugs/UX con contexto de vista.',
    files: 'FeedbackWidget, feedback.ts',
    ipo: {
      input: 'Reporte + screenshot.',
      processing: 'Triage (hoy: archivo).',
      output: 'Nota en disco.',
    },
    suggestedAgentIds: ['omnivoro-nucleo'],
  },
  {
    id: 'research',
    label: 'Cuarentena / Explorador',
    does: 'Puente manual Perplexity (prompt 6×6 + ingest JSON) → hallazgos HITL → aprendizajes IDA.',
    files: 'research.ts, DeprocastCuarentena.tsx (API Sonar opcional en perplexity.ts)',
    ipo: {
      input: 'Tema + JSON pegado (o API futura).',
      processing: 'Parse 6×6 + cuarentena.',
      output: 'Aprendizajes asimilados + embed.',
    },
    suggestedAgentIds: [
      'explorador',
      'explorador-academico',
      'explorador-mercado',
    ],
  },
  {
    id: 'finanzas',
    label: 'Finanzas (ausente)',
    does: 'Todavía no hay módulo. Hueco a propósito.',
    files: '—',
    ipo: {
      input: 'Hechos económicos.',
      processing: 'Clasificar y proyectar.',
      output: 'Libro y flujo.',
    },
    suggestedAgentIds: ['contable', 'tributario'],
  },
  {
    id: 'derecho',
    label: 'Derecho (ausente)',
    does: 'Todavía no hay módulo. Hueco a propósito.',
    files: '—',
    ipo: {
      input: 'Norma, contrato, expediente.',
      processing: 'Tematizar riesgo y plazos.',
      output: 'Ficha jurídica / pacto.',
    },
    suggestedAgentIds: ['legista', 'contractual'],
  },
  {
    id: 'vitalidad',
    label: 'Vitalidad (ausente)',
    does: 'Salud, deporte, nutrición. Cuerpo | Mente | Alma.',
    files: 'Calendario ya tiene el tridente; falta el agente.',
    ipo: {
      input: 'Señal somática, cognitiva, ritual.',
      processing: 'Traducir al tridente.',
      output: 'Ajuste del día.',
    },
    suggestedAgentIds: ['soma', 'noos', 'pneuma', 'entrenador', 'nutricionista', 'medico-archivo'],
  },
]
