import "server-only";

import { ingestKgExtraction } from "@/lib/kg/ingest";
import type { LlmEntity, LlmKgExtraction, LlmRelation } from "@/lib/kg/types";
import {
  buildMetaMeteadorUserPrompt,
  META_METEADOR_SYSTEM_PROMPT,
} from "@/lib/meta-meteador/prompt";
import {
  isValidGeneratedTitle,
  parseMetaMeteadorOutput,
} from "@/lib/meta-meteador/parse";
import type {
  MetaMeteadorAcceptResult,
  MetaMeteadorCoverage,
  MetaMeteadorOutput,
  MetaMeteadorProcessTrace,
  MetaMeteadorRunResult,
  MetaMeteadorSessionItem,
  MetaMeteadorStreamEvent,
} from "@/lib/meta-meteador/types";
import { META_AREAS } from "@/lib/meta-meteador/types";
import {
  countDocumentMeta,
  getDocumentMeta,
  listDocumentMetaIds,
  markDocumentMetaTitleApplied,
  upsertDocumentMeta,
} from "@/lib/meta-meteador/store";
import { extractMarkdownBody, updateTitleInMarkdown } from "@/lib/projects/markdown";
import { findProjectById, listProjects } from "@/lib/projects/service";
import type { Project } from "@/lib/projects/types";
import {
  cohereGenerateText,
  getCohereModelName,
} from "@/lib/cohere/chat";
import { readFile, writeFile } from "node:fs/promises";

const AUTO_TITLE_PATTERN = /sin[-_ ]?titulo/i;

export function isTitleAutoGenerated(title: string): boolean {
  const trimmed = title.trim();
  if (!trimmed) return true;
  if (trimmed.endsWith(".md")) return true;
  if (AUTO_TITLE_PATTERN.test(trimmed)) return true;
  if (/^\d+_/.test(trimmed)) return true;
  return false;
}

const MIN_ANALYZABLE_CHARS = 30;

function buildDocumentBody(project: Project): string {
  const parts = [
    project.description,
    project.resultadoFinal?.trim()
      ? `Resultado final: ${project.resultadoFinal}`
      : "",
    ...project.progressEntries.map(
      (entry) => `Progreso (${entry.fecha}): ${entry.nota}`,
    ),
  ];
  return parts.filter(Boolean).join("\n\n");
}

async function buildAnalyzableBody(project: Project): Promise<string> {
  const structured = buildDocumentBody(project).trim();
  if (structured.length >= MIN_ANALYZABLE_CHARS) {
    return structured;
  }

  const content = await readFile(project.filePath, "utf8");
  const markdownBody = extractMarkdownBody(content);
  if (markdownBody.length >= MIN_ANALYZABLE_CHARS) {
    return markdownBody;
  }

  const combined = [structured, markdownBody].filter(Boolean).join("\n\n").trim();
  if (combined.length >= MIN_ANALYZABLE_CHARS) {
    return combined;
  }

  throw new Error(
    "El documento no tiene contenido analizable (description, cuerpo markdown y bitácora vacíos).",
  );
}

function buildKgProjection(
  output: MetaMeteadorOutput,
  project: Project,
): LlmKgExtraction {
  const entities: LlmEntity[] = [];
  const relations: LlmRelation[] = [];

  const docTitle = output.titulo.trim();

  entities.push({
    name: docTitle,
    type: "documento",
    metadata: {
      documentId: project.id,
      campoSlug: project.campoSlug,
      source: "meta_meteador",
    },
    confidence: 0.9,
  });

  for (const area of META_AREAS) {
    const score = output.areas_relevancia[area].score_1_12;
    entities.push({
      name: area,
      type: "area",
      metadata: { rol: "area_relevancia" },
      confidence: 0.95,
    });
    relations.push({
      fromName: docTitle,
      toName: area,
      relationType: "relevante_para",
      context: `El documento "${docTitle}" tiene relevancia ${score}/12 para el área ${area}.`,
      weight: score,
      confidence: 0.85,
    });
  }

  if (project.title.trim() && project.title.trim() !== docTitle) {
    entities.push({
      name: project.title.trim(),
      type: "proyecto",
      metadata: { projectId: project.id, campoSlug: project.campoSlug },
      confidence: 0.9,
    });
    relations.push({
      fromName: docTitle,
      toName: project.title.trim(),
      relationType: "documenta",
      context: `Metadatos Meta-Meteador vinculados al proyecto ${project.title.trim()}.`,
      weight: 8,
      confidence: 0.9,
    });
  }

  return { entities, relations };
}

async function callMetaMeteador(
  project: Project,
  body: string,
  tituloEsManual: boolean,
): Promise<{
  output: MetaMeteadorOutput;
  rawResponse: string;
  userPrompt: string;
  modelUsed: string;
}> {
  const modelUsed = getCohereModelName("default");
  const userPrompt = buildMetaMeteadorUserPrompt(project, body, tituloEsManual);

  const rawResponse = await cohereGenerateText({
    systemPrompt: META_METEADOR_SYSTEM_PROMPT,
    userContent: userPrompt,
    modelKind: "default",
    jsonMode: true,
  });
  const parsed = parseMetaMeteadorOutput(rawResponse, project.id);
  if (!parsed) {
    throw new Error("La IA no devolvió un JSON de metadatos válido.");
  }

  if (tituloEsManual) {
    parsed.titulo = project.title.trim();
  } else if (!isValidGeneratedTitle(parsed.titulo)) {
    throw new Error(
      `Título generado inválido (${parsed.titulo}): debe tener entre 3 y 7 palabras.`,
    );
  }

  return { output: parsed, rawResponse, userPrompt, modelUsed };
}

async function processDocumentForSession(
  project: Project,
): Promise<MetaMeteadorSessionItem> {
  const tituloEsManual = !isTitleAutoGenerated(project.title);
  const body = await buildAnalyzableBody(project);

  const { output, rawResponse, userPrompt, modelUsed } =
    await callMetaMeteador(project, body, tituloEsManual);

  const meta = output.metadata_del_todo;
  const processTrace: MetaMeteadorProcessTrace = {
    userPrompt,
    rawResponse,
    modelUsed,
    tituloEsManual,
  };

  await upsertDocumentMeta({
    documentId: project.id,
    titulo: output.titulo,
    tituloLocked: tituloEsManual,
    titleApplied: tituloEsManual,
    materia: meta.materia,
    particula: meta.particula,
    campo: meta.campo,
    onda: meta.onda,
    tiempoEspacio: meta.tiempo_espacio,
    posicion: meta.posicion,
    areas: output.areas_relevancia,
    processTrace,
    modelUsed,
  });

  void import("@/lib/historial/log").then(({ logActivity }) =>
    logActivity({
      category: "meta",
      action: "meta_processed",
      title: `Meta-Meteador: ${output.titulo}`,
      summary: meta.particula,
      agentId: "meta-meteador",
      agentName: "Meta-Meteador",
      modelUsed,
      sourceType: "document_meta",
      sourceRef: project.id,
      metadata: { materia: meta.materia, campo: meta.campo },
    }).catch((error) => {
      console.error("Historial meta-meteador log error:", error);
    }),
  );

  const extraction = buildKgProjection(output, project);
  await ingestKgExtraction({
    extraction,
    source: {
      type: "document_meta",
      id: project.id,
      metadata: {
        documentId: project.id,
        titulo: output.titulo,
        source: "meta_meteador",
      },
      confidence: 0.85,
    },
  });

  const canRename =
    !tituloEsManual && output.titulo.trim() !== project.title.trim();

  return {
    documentId: project.id,
    oldFilename: project.filename,
    oldTitle: project.title,
    proposedTitle: output.titulo,
    tituloLocked: tituloEsManual,
    canRename,
    titleApplied: tituloEsManual,
    metadata: meta,
    areas: output.areas_relevancia,
    processTrace,
  };
}

export async function getMetaMeteadorCoverage(): Promise<MetaMeteadorCoverage> {
  const projects = await listProjects();
  const withMeta = await countDocumentMeta();
  return {
    totalDocuments: projects.length,
    withMeta,
    pending: Math.max(0, projects.length - withMeta),
  };
}

export async function listPendingMetaMeteadorProjects(): Promise<Project[]> {
  const projects = await listProjects();
  const existingIds = new Set(await listDocumentMetaIds());
  const seenPendingIds = new Set<string>();
  return projects.filter((project) => {
    if (existingIds.has(project.id)) return false;
    if (seenPendingIds.has(project.id)) return false;
    seenPendingIds.add(project.id);
    return true;
  });
}

export async function* runMetaMeteadorStream(): AsyncGenerator<MetaMeteadorStreamEvent> {
  const projects = await listProjects();
  const existingIds = new Set(await listDocumentMetaIds());
  const seenPendingIds = new Set<string>();
  const pending = projects.filter((project) => {
    if (existingIds.has(project.id)) return false;
    if (seenPendingIds.has(project.id)) return false;
    seenPendingIds.add(project.id);
    return true;
  });

  const summary: MetaMeteadorRunResult = {
    procesados: 0,
    retitulados: 0,
    saltados: projects.length - pending.length,
    errores: [],
  };

  yield {
    type: "start",
    pending: pending.length,
    skipped: summary.saltados,
    total: projects.length,
  };

  if (pending.length === 0) {
    yield { type: "done", summary };
    return;
  }

  for (const project of pending) {
    yield {
      type: "processing",
      documentId: project.id,
      oldFilename: project.filename,
      oldTitle: project.title,
    };

    try {
      const item = await processDocumentForSession(project);
      summary.procesados += 1;
      if (item.canRename) {
        summary.retitulados += 1;
      }
      yield { type: "result", item };
    } catch (error) {
      const message =
        error instanceof Error ? error.message : "Error desconocido";
      summary.errores.push({ documentId: project.id, error: message });
      yield {
        type: "error",
        documentId: project.id,
        oldFilename: project.filename,
        error: message,
      };
    }
  }

  yield { type: "done", summary };
}

export async function runMetaMeteador(): Promise<MetaMeteadorRunResult> {
  let summary: MetaMeteadorRunResult = {
    procesados: 0,
    retitulados: 0,
    saltados: 0,
    errores: [],
  };

  for await (const event of runMetaMeteadorStream()) {
    if (event.type === "done") {
      summary = event.summary;
    }
  }

  return summary;
}

export async function acceptMetaMeteadorTitles(
  items: Array<{ documentId: string; title?: string }>,
): Promise<MetaMeteadorAcceptResult> {
  const result: MetaMeteadorAcceptResult = { applied: 0, errors: [] };

  for (const item of items) {
    try {
      const meta = await getDocumentMeta(item.documentId);
      if (!meta) {
        throw new Error("No hay metadatos Meta-Meteador para este documento.");
      }

      if (meta.tituloLocked || meta.titleApplied) {
        continue;
      }

      const project = await findProjectById(item.documentId);
      if (!project) {
        throw new Error("Proyecto no encontrado.");
      }

      const title = (item.title ?? meta.titulo).trim();
      if (!title) {
        throw new Error("El título no puede estar vacío.");
      }

      if (!isValidGeneratedTitle(title) && !meta.tituloLocked) {
        throw new Error("El título debe tener entre 3 y 7 palabras.");
      }

      const content = await readFile(project.filePath, "utf8");
      const updated = updateTitleInMarkdown(content, title);
      await writeFile(project.filePath, updated, "utf8");
      await markDocumentMetaTitleApplied(item.documentId, title);
      result.applied += 1;
    } catch (error) {
      result.errors.push({
        documentId: item.documentId,
        error: error instanceof Error ? error.message : "Error desconocido",
      });
    }
  }

  return result;
}
