import type { LodBand, SceneNode } from './types'

export const SCENE_NODES: SceneNode[] = [
  {
    id: 'stars',
    label: 'Estrellas',
    kind: 'procedural',
    procedural: 'stars',
    lod: ['cosmic'],
    systems: [],
    color: '#e8e4dc',
  },
  {
    id: 'earth',
    label: 'Tierra',
    kind: 'procedural',
    procedural: 'earth',
    lod: ['cosmic', 'planet'],
    systems: [],
    color: '#3d7ea6',
  },
  {
    id: 'mercury',
    label: 'Mercurio',
    kind: 'procedural',
    procedural: 'mercury',
    lod: ['cosmic', 'planet'],
    systems: [],
    color: '#9a8b7a',
  },
  {
    id: 'rivers',
    label: 'Ríos',
    kind: 'procedural',
    procedural: 'rivers',
    lod: ['landscape'],
    systems: [],
    color: '#4a8fb8',
  },
  {
    id: 'forest',
    label: 'Bosque',
    kind: 'procedural',
    procedural: 'forest',
    lod: ['landscape'],
    systems: [],
    color: '#2d5a3d',
  },
  {
    id: 'paths',
    label: 'Caminos',
    kind: 'procedural',
    procedural: 'paths',
    lod: ['landscape'],
    systems: [],
    color: '#8a7340',
  },
  {
    id: 'skin',
    label: 'Piel',
    kind: 'procedural',
    procedural: 'skin',
    lod: ['body', 'organ'],
    systems: ['integumentary'],
    color: '#c4a07a',
  },
  {
    id: 'skeleton',
    label: 'Esqueleto',
    kind: 'procedural',
    procedural: 'skeleton',
    lod: ['body', 'organ'],
    systems: ['skeletal'],
    color: '#d8d0c4',
  },
  {
    id: 'spine',
    label: 'Columna / médula',
    kind: 'procedural',
    procedural: 'spine',
    lod: ['body', 'organ', 'tissue'],
    systems: ['skeletal', 'nervous'],
    color: '#e8e4dc',
  },
  {
    id: 'heart',
    label: 'Corazón',
    kind: 'procedural',
    procedural: 'heart',
    lod: ['body', 'organ', 'tissue'],
    systems: ['cardiovascular'],
    color: '#c45c4a',
    // Fase 2: url: '/models/heart.glb'
  },
  {
    id: 'vessels',
    label: 'Vasos',
    kind: 'procedural',
    procedural: 'vessels',
    lod: ['body', 'organ', 'tissue'],
    systems: ['cardiovascular'],
    color: '#a33b3b',
  },
  {
    id: 'brain',
    label: 'Cerebro',
    kind: 'procedural',
    procedural: 'brain',
    lod: ['body', 'organ', 'tissue'],
    systems: ['nervous'],
    color: '#c4a0b4',
  },
  {
    id: 'neurons',
    label: 'Neuronas',
    kind: 'procedural',
    procedural: 'neurons',
    lod: ['organ', 'tissue'],
    systems: ['nervous'],
    color: '#d4c4a0',
  },
  {
    id: 'lungs',
    label: 'Pulmones',
    kind: 'procedural',
    procedural: 'lungs',
    lod: ['body', 'organ'],
    systems: ['respiratory'],
    color: '#c4a8b0',
  },
  {
    id: 'liver',
    label: 'Hígado',
    kind: 'procedural',
    procedural: 'liver',
    lod: ['body', 'organ'],
    systems: ['digestive'],
    color: '#8a5a3a',
  },
  {
    id: 'stomach',
    label: 'Estómago',
    kind: 'procedural',
    procedural: 'stomach',
    lod: ['body', 'organ'],
    systems: ['digestive'],
    color: '#b87a6a',
  },
  {
    id: 'kidneys',
    label: 'Riñones',
    kind: 'procedural',
    procedural: 'kidneys',
    lod: ['body', 'organ'],
    systems: ['digestive', 'endocrine'],
    color: '#a06060',
  },
  {
    id: 'thyroid',
    label: 'Tiroides',
    kind: 'procedural',
    procedural: 'thyroid',
    lod: ['body', 'organ'],
    systems: ['endocrine'],
    color: '#c4906a',
  },
  {
    id: 'pituitary',
    label: 'Hipófisis',
    kind: 'procedural',
    procedural: 'pituitary',
    lod: ['organ', 'tissue'],
    systems: ['endocrine'],
    color: '#d4b090',
  },
  {
    id: 'adrenals',
    label: 'Suprarrenales',
    kind: 'procedural',
    procedural: 'adrenals',
    lod: ['organ'],
    systems: ['endocrine'],
    color: '#c47878',
  },
  {
    id: 'pancreas',
    label: 'Páncreas',
    kind: 'procedural',
    procedural: 'pancreas',
    lod: ['organ'],
    systems: ['endocrine', 'digestive'],
    color: '#d4c4a8',
  },
  {
    id: 'lymph',
    label: 'Nodos linfáticos',
    kind: 'procedural',
    procedural: 'lymph',
    lod: ['body', 'organ'],
    systems: ['lymphatic'],
    color: '#6a9e7a',
  },
  {
    id: 'cells',
    label: 'Células',
    kind: 'procedural',
    procedural: 'cells',
    lod: ['micro'],
    systems: [],
    color: '#8ab4c4',
  },
  {
    id: 'bacteria',
    label: 'Bacterias',
    kind: 'procedural',
    procedural: 'bacteria',
    lod: ['micro'],
    systems: [],
    color: '#7a9e6a',
  },
]

export function nodesForBand(band: LodBand): SceneNode[] {
  return SCENE_NODES.filter((n) => n.lod.includes(band))
}

export function findNode(id: string): SceneNode | undefined {
  return SCENE_NODES.find((n) => n.id === id)
}
